services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-terminkalender
    restart: unless-stopped
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reservations_user -d reservations_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
